### ISSUE TITLE
NumericVariant tofloat should be called todouble

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusBase#3]
NumericVariant:

```
    /// \brief Cast to an unsigned integer
    double tofloat() const
    {
        return cast<double>();
    }
```

**Comment by patrickfrey** [comment]
Float is meant as a concept rather than a low level data type.
Variant is an interface data type representing a number than can be integral or a floating point.
For a floating point number representation we chose double. But it could be as well a long double.
For  integer numbers we chose int, but it could as well be a long or long long if available.
